export const nigerianStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export const citiesByState: Record<string, string[]> = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Bende", "Isiala Ngwa"],
  Adamawa: ["Yola", "Mubi", "Numan", "Ganye", "Jimeta", "Shelleng"],
  AkwaIbom: ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak", "Ikot Abasi"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala", "Ogidi"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum", "Ningi"],
  Bayelsa: ["Yenagoa", "Brass", "Nembe", "Ogbia", "Sagbama", "Ekeremor"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya", "Keffi?"],
  Borno: ["Maiduguri", "Biu", "Bama", "Gwoza", "Monguno", "Konduga"],
  CrossRiver: ["Calabar", "Ikom", "Ogoja", "Ugep", "Obudu", "Bakassi"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Abraka", "Effurun"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Ishiagu", "Ezza", "Amasiri"],
  Edo: ["Benin City", "Auchi", "Ekpoma", "Uromi", "Igarra", "Sabongida-Ora"],
  Ekiti: [
    "Ado-Ekiti",
    "Ikere-Ekiti",
    "Ijero-Ekiti",
    "Ikole-Ekiti",
    "Oye-Ekiti",
    "Ise-Ekiti",
    "Emure-Ekiti",
    "Efon-Alaaye",
    "Aramoko-Ekiti",
    "Ilawe-Ekiti",
    "Ifaki-Ekiti",
    "Otun-Ekiti",
    "Omuo-Ekiti",
    "Iyin-Ekiti",
    "Ogotun-Ekiti",
    "Igbara-Odo-Ekiti",
    "Igede-Ekiti",
    "Aisegba-Ekiti",
    "Eda-Ile",
    "Erio-Ekiti",
    "Ode-Ekiti",
    "Araromi-Ekiti",
    "Iyemero-Ekiti",
    "Itapa-Ekiti",
    "Odo-Oro",
    "Ire-Ekiti",
    "Awo-Ekiti",
    "Ikoro-Ekiti",
    "Ise-Orun",
    "Omuo-Oke",
  ],
  Enugu: ["Enugu", "Nsukka", "Oji River", "Agbani", "Awgu", "Udi"],
  "FCT Abuja": ["Abuja", "Gwagwalada", "Kubwa", "Bwari", "Kuje", "Karshi"],
  Gombe: ["Gombe", "Kaltungo", "Dukku", "Billiri", "Bajoga", "Nafada"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta", "Aboh Mbaise"],
  Jigawa: ["Dutse", "Hadejia", "Gumel", "Kazaure", "Birnin Kudu", "Malam Madori"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Kachia", "Giwa", "Saminaka"],
  Kano: ["Kano", "Bichi", "Wudil", "Gaya", "Rano", "Karaye"],
  Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi", "Jibia", "Dutsin-Ma"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Bunza", "Jega"],
  Kogi: ["Lokoja", "Idah", "Okene", "Ankpa", "Kabba", "Ajaokuta"],
  Kwara: ["Ilorin", "Offa", "Omu-Aran", "Patigi", "Lafiagi", "Jebba"],
  Lagos: ["Ikeja", "Lekki", "Surulere", "Ikorodu", "Badagry", "Epe", "Ajah"],
  Nasarawa: ["Lafia", "Keffi", "Akwanga", "Karu", "Nasarawa", "Mararaba"],
  Niger: ["Minna", "Bida", "Suleja", "Kontagora", "Mokwa", "New Bussa"],
  Ogun: ["Abeokuta", "Ijebu-Ode", "Sagamu", "Ilaro", "Ota", "Shagamu"],
  Ondo: ["Akure", "Owo", "Ondo", "Ikare-Akoko", "Okitipupa", "Idanre"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Ikire", "Iwo"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo", "Saki", "Iseyin", "Okeho"],
  Plateau: ["Jos", "Bukuru", "Pankshin", "Shendam", "Vom", "Langtang"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Oyigbo", "Bonny", "Ahoada", "Bori"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno", "Bodinga", "Illela", "Gwadabawa"],
  Taraba: ["Jalingo", "Wukari", "Takum", "Gembu", "Bali", "Sardauna"],
  Yobe: ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam", "Bade"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Tsafe", "Anka", "Maru"],
};